- name: demented_roulette
  wallet:
    group: '2854187674c1e'
  trigger:
  - on_event:
    - contract: DementedRoulette
      event: RoundPlayed
  steps:
    - name: place_bet
      contract: DementedRoulette
      method: placeBet
      arguments:
        - func: generateRandomAmount
        - func: fetchX
    - wallet:
      - selector: random_wallet
  contracts:
    - name: DementedRoulette
      address: '0x94ba26ee118eF6c407c75DbB23385b1AD71a4547'
      abi: /Users/leon/workspace/ensemble/ensemble-service/abi/DGRoulette.abi.json
      network: fuse

# - keepers:
#   - wallets: minimum_balance
#   file: ./src/keepers.js